## Assignment 1 - working with numpy
1.Create a 1D NumPy array with integers from 1 to 20. Perform the following operations:  
 a. Calculate the sum, mean, median, and standard deviation of the elements in the array.  
 b. Find the indices of elements greater than 10 in the array. 


In [ ]:
import numpy as np

In [ ]:
np_array=np.arange(1,21)

In [ ]:
np_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
indices=np.where(np_array>10)

In [ ]:
print("sum:",np.sum(np_array))
print("Mean:",np.mean(np_array))
print("Median:",np.median(np_array))
print("std:",np.std(np_array))
print("Indices for the numbers greater than 10: ",indices)

sum: 210
Mean: 10.5
Median: 10.5
std: 5.766281297335398
Indices for the numbers greater than 10:  (array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19], dtype=int64),)


### Description

I created 1D numpy array of integers 1 to 20 by using arange() function. To Calculate the sum, mean, median, and standard deviation of the elements in the array I have used the builtin functions of numpy like np.sum(),np.mean(),np.median(),np.std().Next The where() funtion is used To Find the indices of elements greater than 10 in the array.

2. Create a 2D NumPy array of shape 4 X 4 with numbers ranging from 1 to 16.  
  a. Print the array.  
  b. Find the transpose of the array.  
  c. Calculate the row-wise and column-wise sums of the array.


In [ ]:
np_array=np.arange(16).reshape(4,4)
np_transpose=np_array.T
np_sum_row=np.sum(np_array,axis=1)# axis=1-row
np_sum_column=np.sum(np_array,axis=0)# axis=0-col

In [ ]:
print("array\n",np_array)
print("\nTranspose\n",np_transpose)
print("\nSum of rows\n",np_sum_row)
print("\nSum of columns\n",np_sum_column)

array
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Transpose
 [[ 0  4  8 12]
 [ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]]

Sum of rows
 [ 6 22 38 54]

Sum of columns
 [24 28 32 36]


### Description

To Create a 2D NumPy array of shape 4 X 4 with numbers ranging from 1 to 16 I used arange()function .To make it in the shape of 4*4 The reshape(4,4) is used.To find the transpose of the array I applied [variable.T] for transpose.To calculate the row wise sum of the array I implemented the np.sum(np_array,axis=1) as well as for column np.sum(np_array,axis=0).here np_array is the variable where i stored the numbers and axis 1 represent the row and axis 0 represent the column.

3. Create two 3 X 3 arrays filled with random integers between 1 and 20.  
  a. Perform element-wise addition, subtraction, and multiplication.  
  b. Compute the dot product of the two arrays.  


In [ ]:
array1=np.random.randint(1,21,(3,3))
array2=np.random.randint(1,21,(3,3))

In [ ]:
array1

array([[13, 18, 12],
       [20, 20, 17],
       [19, 16,  9]])

In [ ]:
array2

array([[ 2,  3,  6],
       [17, 17, 14],
       [10,  3, 13]])

In [ ]:
add=array1+array2
subtract=array1-array2
multiply=array1*array2
dot_product=np.dot(array1,array2)

In [ ]:
print("Addition\n",add)
print("\nsubtraction\n",subtract)
print("\nMultiplication\n",multiply)
print("\nDot product\n",dot_product)

Addition
 [[15 21 18]
 [37 37 31]
 [29 19 22]]

subtraction
 [[11 15  6]
 [ 3  3  3]
 [ 9 13 -4]]

Multiplication
 [[ 26  54  72]
 [340 340 238]
 [190  48 117]]

Dot product
 [[452 381 486]
 [550 451 621]
 [400 356 455]]


### Description

To create two 3 X 3 arrays filled with random integers between 1 and 20 I started with random.randint(1,21,(3,3)) and stored it in two variables named array1 and array2.To perform operations such as addition ,subtraction,multiplication I have used the operators such as '+','-','*' respectively.For the dot product i have used the np.dot(array1,array2) builtin function.finallyI used print function to print it out. 



4. Reshape a 1D array of size 12 into a 3 X 4 2D array and slice the first two rows and last two columns.  

In [ ]:
array=np.arange(1,13).reshape(3,4)
a=array[:2]
b=array[:,-2:]

In [ ]:
print("array\n",array)
print("\nslicing first 2 rows\n",a)
print("\nslicing last 2 columns\n",b)

array
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

slicing first 2 rows
 [[1 2 3 4]
 [5 6 7 8]]

slicing last 2 columns
 [[ 3  4]
 [ 7  8]
 [11 12]]


### Description

To reshape a 1D array of size 12 into 3*4 i used np.arange(1,13).reshape(3,4) to store the numbers from 1 to 12 and reshape it to 3*4 and named the variable as array.to slice first 2 rows and last 2 columns i have used slice function array[:2] for rows and array[;,-2;]for columns